{% set version = "2.4.0" %}

package:
  name: gdal-split
  version: {{ version }}

source:
  url: http://download.osgeo.org/gdal/{{ version }}/gdal-{{ version }}.tar.xz
  sha256: c3791dcc6d37e59f6efa86e2df2a55a4485237b0a48e330ae08949f0cdf00f27
  patches:
  patches:
    # BUILT_AS_DYNAMIC_LIB.
    - patches/windowshdf5.patch  # [win]
    # Use multiple cores on Windows.
    - patches/multiprocessor.patch  # [win]
    # disable 12 bit jpeg on Windows as we aren't using internal jpeg
    - patches/disable_jpeg12.patch  # [win]

build:
  number: 1005
  skip: True  # [win and vc<14]

requirements:
  build:
    - cmake  # [win]
    - pkg-config >=0.21  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - m2-patch  # [win]
  host:
    - curl
    - expat
    - freexl
    - geos
    - geotiff
    - giflib  # [not win]
    - hdf4
    - hdf5
    - jpeg
    - json-c  # [not win]
    - kealib
    - libdap4  # [not win]
    - libkml
    - libnetcdf
    - libpng
    - libpq
    - libspatialite
    - libtiff
    - libuuid  # [linux]
    - libxml2
    - openjpeg
    - openssl
    - pcre
    - poppler
    - postgresql
    - proj4
    - sqlite
    - xerces-c
    - xz  # [not win or vc>=14]
    - m2w64-xz  # [win]
    - zlib

outputs:
  - name: libgdal
    script: install_lib.sh   # [unix]
    script: install_lib.bat   # [win]
    build:
      run_exports:
        # no idea, going with minor pin
        - {{ pin_subpackage('libgdal', max_pin='x.x') }}
    requirements:
      build:
        # ranlib used at install time
        - {{ compiler('c') }}
        # libstdc++ is needed in requirements/run
        - {{ compiler('cxx') }}
        - pkg-config  # [not win]
        - m2-patch  # [win]
      host:
        - curl
        - expat
        - freexl
        - geos
        - geotiff
        - giflib  # [not win]
        - hdf4
        - hdf5
        - jpeg
        - json-c  # [not win]
        - kealib
        - libdap4  # [not win]
        - libkml
        - libnetcdf
        - libpng
        - libpq
        - libspatialite
        - libtiff
        - libuuid  # [linux]
        - libxml2
        - openjpeg
        - openssl
        - pcre
        - poppler
        - postgresql
        - proj4
        - sqlite
        - xerces-c
        - xz  # [not win or vc>=14]
        - m2w64-xz  # [win]
        - zlib
      run:
        - geotiff
        - giflib  # [not win]
        - json-c  # [not win]
        - libdap4  # [not win]
        - libpq
        - libspatialite
        - libuuid  # [linux]
        - poppler
        - postgresql
        - proj4
        - xz  # [not win or vc>=14]
        - m2w64-xz  # [win]
    test:
      files:
        - test_data
      commands:
        - gdal_grid --version
        - gdal_rasterize --version
        - gdal_translate --version
        - gdaladdo --version
        - gdalenhance --version
        - gdalwarp --version
        - gdalinfo --formats
        - gdalinfo http://thredds.nersc.no/thredds/dodsC/greenpath/Model/topaz  # [not win]
        - {{ RECIPE_DIR }}\\run_test.bat  # [win]
        - bash {{ RECIPE_DIR }}/run_test.sh  # [not win]
    about:
      summary: 'The Geospatial Data Abstraction Library (GDAL)'

  - name: gdal
    script: install_python.sh
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake  # [win]
        - m2-patch  # [win]
        - m2-bash  # [win]
      host:
        - python
        - pip
        - numpy
        - {{ pin_subpackage('libgdal', exact=True) }}
      run:
        - python
        - {{ pin_compatible('numpy') }}
        - {{ pin_subpackage('libgdal', exact=True) }}
    test:
      files:
        - test_data
        - extra_tests.py
      imports:
        - osr
        - gdal
        - gdalconst
        - osgeo
        - osgeo.ogr
        - osgeo.gdal
        - osgeo._gdal
        - osgeo._gdalconst
        - osgeo._ogr
        - osgeo._osr
      commands:
        - python {{ RECIPE_DIR }}/run_test.py
      about:
        summary: 'Python wrapper for the Geospatial Data Abstraction Library (GDAL)'

about:
  home: http://www.gdal.org
  license: MIT
  license_file: LICENSE.TXT
  summary: |
    GDAL is a translator library for raster and vector geospatial data formats that is released under an
    X/MIT style Open Source license by the Open Source Geospatial Foundation.

extra:
  recipe-maintainers:
    - gillins
    - kmuehlbauer
    - mingwandroid
    - msarahan
    - ocefpaf
